name: Lab5

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Access
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      run: ./gradlew wrapper --gradle-version 6.8.3

    - name: Build with Gradle
      run: ./gradlew build

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Publish package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish
        env:
          GH_USERNAME: artemlevv
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
