name: Lab5

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Access
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      run: ./gradlew wrapper --gradle-version 6.8.3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish JAR Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Lab5-CI
        path: build/libs/*.jar

  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
