name: Lab5

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Access
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      run: ./gradlew wrapper --gradle-version 6.8.3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish JAR Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Lab5-CI
        path: build/libs/*.jar
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone repository to upload artifact
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: Lab5-CI
        path: build/libs

    - name: Commit artifact to repository
      run: |
        git add build/libs/*.jar
        git commit -m "Add artifact from GitHub Actions build ${{ github.run_number }}"
        git push

  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
